### ISSUE TITLE
rpmrepo returns 500 Internal Server Error on malformed paths

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/rpmci#1]
rpmrepo returns `500 Internal Server Error` when the path component of the URL contains repeated slashes (`"//"`). Even though slashes could be folded into one server-side (because `a//b` *usually* has the same meaning as `a/b`), I think it would be fine to return `404 Not Found` on them as well. A server error might point to a real issue, though.

This happens using both the `anon` and (redhat-internal) `psi` storages:
```
$ curl -Lf https://rpmrepo.osbuild.org/v1/anon/f32/f32-x86_64-fedora-20201010//Packages/a/acl-2.2.53-5.fc32.x86_64.rpm
curl: (22) The requested URL returned error: 500 
$ curl -Lf https://rpmrepo.osbuild.org/v1/psi/f32/f32-x86_64-fedora-20201010/Packages/a/acl-2.2.53-5.fc32.x86_64.rpm
curl: (22) The requested URL returned error: 404 Not Found

$ curl -Lf https://rpmrepo.osbuild.org/v1/psi/f32/f32-x86_64-fedora-20201010//Packages/a/acl-2.2.53-5.fc32.x86_64.rpm
curl: (22) The requested URL returned error: 500 
$ curl -Lf https://rpmrepo.osbuild.org/v1/psi/f32/f32-x86_64-fedora-20201010/Packages/a/acl-2.2.53-5.fc32.x86_64.rpm
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by dvdhrm** [comment]
It returns 403/404 now. Note that this uses AWS API Gateway, so I do not control the error-codes returned if the URL does not match one of the possible APIs. At least I am unaware of the right knob for that.

Regardless, I don't see how I could merge repeating slashes in API Gateway. But good to keep that in mind.

**Comment by larskarlitski** [comment]
> It returns 403/404 now. Note that this uses AWS API Gateway, so I do not control the error-codes returned if the URL does not match one of the possible APIs. At least I am unaware of the right knob for that.

Thanks! Seems like it's 403 for unmatched paths, which works for me.

> Regardless, I don't see how I could merge repeating slashes in API Gateway. But good to keep that in mind.

I don't think there's a need to. Like I said above, it's fine to return `404`.
