### ISSUE TITLE
Create Fedora snapshots for alternative architectures

### ISSUE THREAD

**Issue by msehnout** [osbuild/rpmci#2]
We use these repos for depsolving test and it would be nice to have all of them as a snapshot.

**Comment by dvdhrm** [comment]
`aarch64`, `ppc64le`, and `s390x` are now available as well. The snapshots are still running, but the base repository snapshots are done.

This did increase snapshot-times significantly, btw. Now takes >24h with 6 machines running.

**Comment by dvdhrm** [comment]
This is done now! :)
